// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var SERVICES = [
  {
    id: "residential",
    name: "Residential Cleaning",
    summary: "Detailed home cleans, kitchens, bathrooms, floors, recurring or one-time support."
  },
  {
    id: "commercial",
    name: "Commercial Cleaning",
    summary: "Offices and businesses. Dependable scheduling, sanitation-focused work, professional presentation."
  },
  {
    id: "vehicle",
    name: "Vehicle Detailing",
    summary: "Interior and exterior detailing, mats, windows, vacuuming, deodorizing, clear coat protectant. Larger vehicles may cost more."
  },
  {
    id: "yard",
    name: "Yard & Seasonal Maintenance",
    summary: "Mowing, edging, trimming, lawn aeration, dethatching, weed removal, snow removal, and garbage cleanup."
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List the services JAMI Cleaning Inc offers in Grande Prairie, Alberta.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});
var SERVICE_DETAILS = {
  residential: {
    includes: [
      "Kitchens, bathrooms, floors, dusting, surfaces",
      "One-time deep cleans or recurring service",
      "Trained, reliable staff"
    ]
  },
  commercial: {
    includes: [
      "Offices, clinics, retail, and shared spaces",
      "Dependable scheduling around business hours",
      "Sanitation-focused cleaning for client-facing areas"
    ]
  },
  vehicle: {
    includes: [
      "Interior and exterior detailing",
      "Mats, windows, vacuuming, deodorizing",
      "Clear coat protectant"
    ],
    notes: "Larger vehicles (trucks, SUVs, RVs) may cost more."
  },
  yard: {
    includes: [
      "Mowing, edging, trimming",
      "Lawn aeration, dethatching, weed removal",
      "Snow removal and garbage cleanup"
    ]
  }
};
var ServiceIdSchema = z.enum(["residential", "commercial", "vehicle", "yard"]);

// src/lib/mcp/tools/get-service-details.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_service_details_default = defineTool2({
  name: "get_service_details",
  title: "Get service details",
  description: "Get the included items and any pricing notes for a specific JAMI Cleaning service.",
  inputSchema: {
    service_id: z2.enum(["residential", "commercial", "vehicle", "yard"]).describe("The service id. One of: residential, commercial, vehicle, yard.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ service_id }) => {
    const service = SERVICES.find((s) => s.id === service_id);
    const details = SERVICE_DETAILS[service_id];
    if (!service || !details) {
      return {
        content: [{ type: "text", text: `Unknown service: ${service_id}` }],
        isError: true
      };
    }
    const payload = { ...service, ...details };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var CONTACT = {
  business_name: "JAMI Cleaning Inc",
  location: "Grande Prairie, Alberta",
  owners: ["Ramin Jami", "Leila Jami"],
  phones: ["780-897-3077"],
  email: "Accounting@jamicleaninginc.com",
  social: { instagram: "@jamicleaninginc" },
  hours: "Monday-Friday, 8:00 AM to 10:00 PM",
  service_area: "Grande Prairie, Wembley, Clairmont, and the County of Grande Prairie, Alberta",
  canadian_owned: true
};
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return phone numbers, email, hours, location, and social handle for JAMI Cleaning Inc.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACT, null, 2) }],
    structuredContent: CONTACT
  })
});

// src/lib/mcp/tools/get-trust-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var TRUST = {
  credentials: [
    "Licensed, bonded, and insured",
    "10+ years in the cleaning industry",
    "Locally owned and operated in Grande Prairie"
  ],
  guarantees: [
    "Re-cleaning guarantee within 24 hours if you are not satisfied",
    "Competitive rates with price matching",
    "Ask about our zero cancellation fee policy"
  ],
  certifications: [
    "WHMIS",
    "Personal Protective Equipment",
    "Bloodborne Pathogens",
    "Ladder Safety",
    "Pandemic Awareness"
  ],
  rating: { source: "Google", stars: 4.6, review_count: 9 }
};
var get_trust_info_default = defineTool4({
  name: "get_trust_info",
  title: "Get trust and guarantee info",
  description: "Return credentials, guarantees, certifications, and public review rating for JAMI Cleaning Inc.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(TRUST, null, 2) }],
    structuredContent: TRUST
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jami-cleaning-mcp",
  title: "JAMI Cleaning",
  version: "0.1.0",
  instructions: "Public tools for JAMI Cleaning Inc, a residential and commercial cleaning, vehicle detailing, and yard maintenance company in Grande Prairie, Alberta. Use `list_services` to see what is offered, `get_service_details` for what a specific service includes, `get_contact_info` for phone/email/hours, and `get_trust_info` for credentials and guarantees.",
  tools: [list_services_default, get_service_details_default, get_contact_info_default, get_trust_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
